[package]
name = "noontide-emu"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
bus = "2.3.0"
clap = { version = "4.1.4", features = ["derive"] }
crossterm = "0.25.0"
itertools = "0.10.5"
tui = "0.19.0"

[features]
debugger = []
